### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by mathix420** [rafgraph/rollpkg#4]
When running `rollpkg build` I got the following error:

```
/node_modules/rollpkg/dist/configureRollpkg.js:60
    errorUtils_1.invariant(isValidName.validForNewPackages, `Invalid npm package name, see https://www.npmjs.com/package/validate-npm-package-name\n${isValidName.errors?.length
                                                                                                                                                                         ^
SyntaxError: Unexpected token '.'
```
After replacing `isValidName.errors?.length` by `isValidName.errors && isValidName.errors.length` I got

```
/node_modules/rollpkg/dist/configureRollpkg.js:62
            ?.map((npmError) => `Npm Error: ${npmError}`)
             ^
SyntaxError: Unexpected token '.'
```
After fixing this the command runs successfully.

**Versions:**
```
npm: 7.6.1
node: 12.14.1
typescript: ^4.2.3
rollpkg: ^0.5.0
```

**Comment by rafgraph** [comment]
Please upgrade to node v14. Optional chaining `?.` isn’t supported by node v12.

**Comment by mathix420** [comment]
Ok I see thanks for your response!

**Comment by rafgraph** [comment]
Rollpkg v0.5.2 (just released) should support node v12. I changed the build target to ES2018 which transpilies optional chaining `?.`.

**Comment by mathix420** [comment]
Working fine on node v12 with `rollpkg@0.5.2`! Nice work!
