### ISSUE TITLE
TypeScript Error: failed to transpile tslib.es6.js

### ISSUE THREAD

**Issue by mathix420** [rafgraph/rollpkg#5]
Here is all my config hope it help fixing an issue!
```
> rollpkg build

✓ Cleaning dist folder 1 ms
✓ Checking rollpkg invariants 3 ms
✓ Creating rollup config 0 ms
✗ FAILED AT: Creating esm, cjs builds

TypeScript Error: failed to transpile '[...]/node_modules/tslib/tslib.es6.js'
```

`tsconfig.json`
```json
{
    "extends": "rollpkg/configs/tsconfig.json",
    "compilerOptions": {
        "target": "es5",
        "lib": ["esnext"],
        "module": "esnext",
        "moduleResolution": "node",
        "rootDir": "./src",
        "strict": true,
    },
    "include": ["src" ],
    "exclude": [
        "node_modules",
        "**/tests/*",
        "dist"
    ]
}
```

`package.json`
```json
{
  [...]

  "name": "vuito",
  "main": "dist/vuito.cjs.js",
  "module": "dist/vuito.esm.js",
  "types": "dist/index.d.ts",
  "sideEffects": false,
  "files": ["dist"],

  [...]
}
```

**Comment by rafgraph** [comment]
Not sure about this.. does upgrading to node v14 help?

Does it work if you don’t add any tsconfig overrides to the extended config?

Also note that if you’re using any web apis you’ll need to add `dom` to the tsconfig `lib` field.

**Comment by rafgraph** [comment]
I was able to reproduce it, I think it's related to an updated dependency and `"target": "es5"`. In the mean time Rollpkg `v0.4.2` should work fine.
```
npm i --save-dev --save-exact rollpkg@0.4.2
```

**Comment by rafgraph** [comment]
The culprit was `rollup-plugin-typescript2`, I had to downgrade to `v0.29.0`. I just published Rollpkg `v0.5.1`, this should fix the issue.

**Comment by mathix420** [comment]
Alright, thanks for your time and this great lib!
Have a nice day!

**Comment by rafgraph** [comment]
@mathix420 when you have a chance can you confirm that v0.5.1 fixes your issue, thanks.

**Comment by mathix420** [comment]
Yes, `v0.5.1` fixes this issue!
As my project gone more complex I ended up using a manual rollup config, but I created a branch with the rollpkg if you want to check https://github.com/mathix420/vuito/tree/rollpkg
