### ISSUE TITLE
Bundlephobia Error: BuildError

### ISSUE THREAD

**Issue by bpierre** [rafgraph/rollpkg#7]
I started to get this error at some point and I’m not sure how to fix it. I was wondering if there was a way to get detailled Bundlephobia errors with rollpkg?

This is the project I am refering to: https://github.com/spectrexyz/use-nft

**Comment by rafgraph** [comment]
This is likely due to a cache error in Bundlephobia's `package-build-stats`. The cache is stored at `/tmp/tmp-build`, you can `cd /tmp && rm -rf tmp-build` and this should fix the error.

It's not possible to get detailed Bundlephobia errors from Rollpkg currently, but I think it makes sense to add this.

**Comment by rafgraph** [comment]
Just added the full Bundlephobia error to the console output. Please upgrade to Rollpkg `v0.5.3`.

**Comment by bpierre** [comment]
Awesome, thank you :heart: 

The error was coming from using the optional chaining operator (`?.`), which bundlephobia doesn’t appear to parse.

**Comment by bpierre** [comment]
Adding the output just in case you want to see the full error:

```console
✓ Cleaning dist folder 8 ms
✓ Checking rollpkg invariants 7 ms
✓ Creating rollup config 0 ms
✓ Creating esm, cjs builds 2.2 secs
✓ Writing esm, cjs builds 584 ms
✓ ROLLPKG BUILD SUCCESS 😁😘 0 ms
✗ FAILED AT: Calculating Bundlephobia stats

Bundlephobia Error: BuildError

BuildError: BuildError
    at Object.buildPackage (/home/pierre/s/use-nft/node_modules/package-build-stats/build/utils/build.utils.js:221:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.buildPackageIgnoringMissingDeps (/home/pierre/s/use-nft/node_modules/package-build-stats/build/utils/build.utils.js:288:27)
    at async Promise.all (index 1)
    at async Object.getPackageStats (/home/pierre/s/use-nft/node_modules/package-build-stats/build/getPackageStats.js:89:48)
    at async Object.calculateBundlephobiaStats (/home/pierre/s/use-nft/node_modules/rollpkg/dist/bundlephobiaStats.js:35:30)
    at async Object.progressEstimator (/home/pierre/s/use-nft/node_modules/progress-estimator/src/logger.js:58:27)
    at async rollpkg (/home/pierre/s/use-nft/node_modules/rollpkg/dist/cli.js:164:13) {
  originalError: [
    '/tmp/tmp-build/packages/build-use-nft-9ip/node_modules/use-nft/dist/use-nft.esm.js 113:32\n' +
      'Module parse failed: Unexpected token (113:32)\n' +
      'File was processed with these loaders:\n' +
      ' * ./node_modules/shebang-loader/index.js\n' +
      ' * ./node_modules/string-replace-loader/index.js\n' +
      'You may need an additional loader to handle the result of these loaders.\n' +
      '|     return (_data.title === "Asset Metadata" &&\n' +
      '|         _data.type === "object" &&\n' +
      '>         typeof _data.properties?.name?.description === "string" &&\n' +
      '|         typeof _data.properties?.image?.description === "string" &&\n' +
      '|         typeof _data.properties?.description?.description === "string" &&\n' +
      ' @ /tmp/tmp-build/packages/build-use-nft-9ip/index.js 1:10-28'
  ],
  extra: undefined
}
```

Also the command exits with a code `0`, not really a problem for me but I wonder if it should exit with `1` or something else when the stats generation fail?

**Comment by rafgraph** [comment]
Thanks for the info. Rollpkg will exit `1` when the build fails, and `0` when the build succeeds (even if the stats calculation fails). Bundlephobia stats calc can be finicky and is generally not critical, so I don’t want it block scripts that run after the build, like publishing the package, etc.

**Comment by bpierre** [comment]
Agreed, it seems like a better strategy for now.

**Comment by rafgraph** [comment]
Regarding the optional chaining operator `?.`, if you set `"target": "ES2018"` in your `tsconfig` Rollpkg will transform it (`?.` is part of the ES2020 spec).

**Comment by bpierre** [comment]
Ah yes I am using `ES2020` on purpose, but I might revert to `ES2018` if it’s too much of a hassle.

There is a PR on `package-build-stats` that should fix the issue, but it doesn’t seem quite ready yet: https://github.com/pastelsky/package-build-stats/pull/34

Thanks!
