### ISSUE TITLE
Dependency "package-build-stats" is too big

### ISSUE THREAD

**Issue by hyrious** [rafgraph/rollpkg#8]
Because it does bundle everything in your package with webpack to calculate the  stats, it is very big:

```
❯ npm i -D package-build-stats
❯ du -h -d 1 node_modules | sort -shr | head
374M	node_modules
161M	node_modules/node-sass
 17M	node_modules/rxjs
9.8M	node_modules/prettier
8.9M	node_modules/@types
8.7M	node_modules/esbuild-loader
7.8M	node_modules/esbuild
7.7M	node_modules/webpack
7.1M	node_modules/core-js
7.0M	node_modules/svelte
```

Would you consider move it to optionalDependencies?

**Comment by rafgraph** [comment]
Hi, yeah I'd consider it. I'm not familiar with optionalDependencies... how would that work? Feel free to make a PR.

**Comment by rafgraph** [comment]
Closing, see #9 for explanation.
